
version: 2.1

  jobs:

    docker:
      - image: cimg/base:2022.05
      
      steps:
        - run:
            name: Install Dependencies
            command: bundle install

        - run:
            name: Setup Database
            environment:
              RAILS_ENV: test
              POSTGRES_HOST: localhost
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: ci_db_test
            command: |
              cp config/database.yml.ci config/database.yml
              bundle exec rails db:create
              bundle exec rails db:schema:load

        - run:
            name: Run RSpec
            environment:
              RAILS_ENV: test
              POSTGRES_HOST: localhost
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: ci_db_test
            command: bundle exec rspec

        - image: circleci/postgres:11
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ci_db_test
    
workflows:
   rspec test: 
     jobs:
