version: 2.1
executors:
  default_image:
    docker:
    - image: cimg/base:current
    - image: cimg/ruby:2.6.6
jobs:
  build:
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ci_db_test
      POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      SELENIUM_URL: http://chrome:4444/wd/hub
    executor: default_image
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: bundle install
    - run:
        command: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rspec
workflows:
  main:
    jobs:
    - build
