version: 2.1
executors:
  default_image:
    docker:
    - image: cimg/ruby:2.6.6-node
    - image: circleci/postgres:11.9
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
jobs:
  build:
    executor: default_image
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ci_db_test
      POSTGRES_PORT: 5432
      POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      SELENIUM_URL: http://chrome:4444/wd/hub
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: bundle install
    - run:
          name: Setup Database
          command: |
            cp config/database.yml.ci config/database.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load
    - run:
          name: Run RSpec
          command: bundle exec rspec

workflows:
  main:
    jobs:
    - build
