version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: bundle install


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
                - release
                - feature/*