name: RSpec Tests

on:
  pull_request:
    types: [opened, assigned, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Install dependencies
        run: bundle install 

      - name: Create test database
        run: bundle exec rake db:create db:schema:load --trace

      - name: Run RSpec
        run: bundle exec rspec
