name: RSpec Tests

on:
  pull_request:
    types: [opened, assigned, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          
      - name: Install dependencies
        run: bundle install 

      - name: Run RSpec
        run: bundle exec rspec
