name: movie

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle install 

    - name: Run tests
      run: bundle exec rspec  

    - name: Update PR status
      if: ${{ always() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Test results:
          - Status: ${{ job.status }}
          - Conclusion: ${{ job.status == 'success' && 'success' || 'failure' }}
