name: RSpec Tests

on:
  pull_request:
    types: [opened, assigned]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.3
          
      - name: Install dependencies
        run: bundle install 

      - name: Run RSpec
        run: bundle exec rspec
